name: Deploy Express to AWS ECS (Public ECR)

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  ECR_PUBLIC_REGISTRY: public.ecr.aws/r7c1c8z5
  ECR_REPOSITORY_EXPRESS: express-app
  ECS_CLUSTER: my-first-cluster
  ECS_TASK_DEFINITION: .aws/ecs-task-definition.json
  ECS_SUBNET: subnet-033e289b7b67bf8df
  ECS_SECURITY_GROUP: sg-02c3702cfa8399f6e

jobs:
  deploy:
    name: Build & Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login en Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Construir y subir imagen de Express a ECR Public
        run: |
          IMAGE_TAG=latest
          IMAGE_URL=$ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY_EXPRESS:$IMAGE_TAG
          
          docker build -t $IMAGE_URL ./express
          docker push $IMAGE_URL
          
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

      - name: Imprimir URL de la imagen subida
        run: |
          echo "La imagen está disponible en: $IMAGE_URL"

      - name: Obtener la última versión de la tarea
        run: |
          LATEST_TASK_DEFINITION=$(aws ecs list-task-definitions \
            --family-prefix express-mongo-task \
            --sort DESC \
            --query 'taskDefinitionArns[0]' \
            --output text)
          echo "LATEST_TASK_DEFINITION=$LATEST_TASK_DEFINITION" >> $GITHUB_ENV

      - name: Verificar si hay tareas en ejecución y detenerlas
        run: |
          RUNNING_TASKS=$(aws ecs list-tasks --cluster $ECS_CLUSTER --desired-status RUNNING --query 'taskArns' --output text)
          
          if [ -n "$RUNNING_TASKS" ]; then
            echo "Deteniendo tareas en ejecución..."
            for TASK in $RUNNING_TASKS; do
              aws ecs stop-task --cluster $ECS_CLUSTER --task $TASK
            done
            echo "TASKS_BEING_STOPPED=$RUNNING_TASKS" >> $GITHUB_ENV
          else
            echo "No hay tareas en ejecución."
          fi

      - name: Esperar a que la tarea anterior se detenga completamente
        run: |
          if [ -n "$TASKS_BEING_STOPPED" ]; then
            for i in {1..10}; do
              STOPPED_TASKS=$(aws ecs list-tasks --cluster $ECS_CLUSTER --desired-status STOPPED --query 'taskArns' --output text)
              
              if [ "$STOPPED_TASKS" == "$TASKS_BEING_STOPPED" ]; then
                echo "Las tareas se han detenido completamente."
                break
              fi
              
              echo "Esperando 10 segundos para verificar nuevamente..."
              sleep 10
            done
          fi

      - name: Ejecutar una nueva tarea en ECS
        run: |
          TASK_ARN=$(aws ecs run-task --cluster $ECS_CLUSTER \
            --task-definition $LATEST_TASK_DEFINITION \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[$ECS_SUBNET],securityGroups=[$ECS_SECURITY_GROUP],assignPublicIp=ENABLED}" \
            --query 'tasks[0].taskArn' --output text)
          
          echo "TASK_ARN=$TASK_ARN" >> $GITHUB_ENV

      - name: Esperar a que la tarea obtenga una IP pública
        run: |
          echo "Esperando a que la tarea tenga una IP pública..."
          
          for i in {1..10}; do
            NETWORK_INTERFACE_ID=$(aws ecs describe-tasks --cluster $ECS_CLUSTER --tasks $TASK_ARN \
              --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value' --output text)
            
            if [ -n "$NETWORK_INTERFACE_ID" ]; then
              break
            fi
            echo "Esperando 5 segundos..."
            sleep 5
          done

          echo "NETWORK_INTERFACE_ID=$NETWORK_INTERFACE_ID" >> $GITHUB_ENV

      - name: Obtener y mostrar la IP pública de la tarea
        run: |
          PUBLIC_IP=$(aws ec2 describe-network-interfaces \
            --network-interface-ids $NETWORK_INTERFACE_ID \
            --query 'NetworkInterfaces[0].Association.PublicIp' \
            --output text)

          echo "La IP pública de la tarea es: $PUBLIC_IP"
