name: Deploy Express to AWS ECS (Public ECR)

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  ECR_PUBLIC_REGISTRY: public.ecr.aws/r7c1c8z5
  ECR_REPOSITORY_EXPRESS: express-app
  ECS_CLUSTER: my-cluster
  ECS_SERVICE: express-service
  ECS_TASK_DEFINITION: .aws/ecs-task-definition.json

jobs:
  deploy:
    name: Build & Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login en Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Construir y subir imagen de Express a ECR Public
        run: |
          docker build -t $ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY_EXPRESS:latest ./express
          docker push $ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY_EXPRESS:latest

      - name: Actualizar definición de tarea ECS
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
